### ISSUE TITLE
wrong pagination

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav-plugin-pagination#39]
Hi
pagination error
my header
```
---
title: Home
body_classes: 'title-center title-h1h2'
content:
    items:
        - '@self.children'
    limit: 16
    order:
        by: date
        dir: desc
    pagination: true
    url_taxonomy_filters: true
---
```

I use
```
{% set articlespubl = taxonomy.findTaxonomy({'tag':'publ'}) %}
                {% for post in articlespubl.order('date','desc') %}
                      {% include 'partials/blog-list-item-post.html.twig' with {blog: page, page: child} %}
                {% endfor %}

```
and recive 11 post in page, and 1-2 pagination with two identical page (1,2)
