### ISSUE TITLE
Pagination gets cached. All the pages look same

### ISSUE THREAD

**Issue by u07** [getgrav/grav-plugin-pagination#62]
Hi,
Can anyone explain how the Pagination plugin is supposed to work alongside Grav’s caching mechanism? In my case, a simple example gets heavily cached, so I can only navigate through pages one and two. After that, pages 3, 4, 5, etc., display the content of page two until I manually press the Clear Cache button.

I don't feel like disabling caching entirely, though. Or should I? 

Listing page:
``` twig

---
title: 'Главная страница'
body_classes___: 'title-center title-h1h2'
taxonomy:
    category:
        - Главная
        - Страница
visible: false
content:
    items:
        - '@page.children': /tools
        - '@page.children': /notes
    limit: 10
    pagination: true
    order:
        by: date
        dir: desc
process:
    markdown: true
    twig: true
twig_first: true
---

# Главная страница

{% set collection = page.collection() %}
{% do paginate(collection, collection.params.limit) %}

{% include 'partials/list_articles.html.twig' with { collection: collection } %}

{% if config.plugins.pagination.enabled and page.collection().params.pagination %}
    {% include 'partials/pagination.html.twig' with {'base_url':page.url, 'pagination':page.collection().params.pagination} %}
{% endif %}

```

Rendering partial:

``` html

<ul>
    {% for article in collection if (not article.header.pp_protect) and (article.routable) and (article.header.visible is not same as(false)) %}
	
    <li>
		<a href="{{ article.url }}">
		{% set logo = article.media.images|first %}
		{% if logo %} {{ logo.cropZoom(350,180).quality(60).attribute('class', mode)|raw }}
        {% else %}	{{ media[include('partials/rnd-img.twig', {seed:article.date})|raw].cropZoom(350,180).quality(60).html('Случайная картинка', 'Случайная картинка', mode)|raw }} 
        {% endif %}        
		<div class="img-capt">{{ article.title }}</div>
		</a>
		
		 <pre>
        {{ dump(article.title, article.header.pp_protect, article.routable, article.header.visible) }}
    </pre>
	
    </li>
    {% endfor %}
</ul>


```

**Comment by u07** [comment]
system.yaml

```yaml
cache:
  enabled: true
  check:
    method: file
  driver: file
  prefix: g
  purge_at: '0 4 * * *'
  clear_at: '0 3 * * *'
  clear_job_type: standard
  clear_images_by_default: false
  cli_compatibility: false
  lifetime: 21600
  gzip: true
  allow_webserver_gzip: false
  redis:
    socket: '0'
    password: null
    database: null
    server: null
    port: null
  memcache:
    server: 127.0.0.1
    port: '11211'
  memcached:
    server: 127.0.0.1
    port: '11211'
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: true
  undefined_functions: true
  undefined_filters: true
  safe_functions: {  }
  safe_filters: {  }
  umask_fix: false
```
